import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { API } from "../api/client";

export default function SharePage() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`${API}/papers/${id}/share-digest`)
      .then((r) => { if (!r.ok) throw new Error("Not found"); return r.json(); })
      .then(setData)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return (
    <div className="min-h-screen bg-surface flex items-center justify-center">
      <div className="text-center">
        <svg className="animate-spin h-8 w-8 text-primary mx-auto mb-3" viewBox="0 0 24 24" fill="none">
          <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" className="opacity-25" />
          <path d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" fill="currentColor" className="opacity-75" />
        </svg>
        <p className="text-on-surface-variant">Loading digest...</p>
      </div>
    </div>
  );

  if (error || !data) return (
    <div className="min-h-screen bg-surface flex items-center justify-center">
      <div className="text-center">
        <span className="material-symbols-outlined text-5xl text-outline-variant/40 mb-3 block">error</span>
        <p className="text-on-surface-variant">{error || "Paper not found"}</p>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-surface">
      <header className="bg-primary px-8 py-4">
        <div className="max-w-[700px] mx-auto flex items-center gap-3">
          <div className="w-8 h-8 bg-white/20 rounded-lg flex items-center justify-center">
            <span className="material-symbols-outlined text-white text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>school</span>
          </div>
          <h1 className="text-white font-bold text-lg">ScholarFlow</h1>
          <span className="text-white/60 text-[12px] ml-auto">Shared Digest</span>
        </div>
      </header>
      <main className="max-w-[700px] mx-auto px-8 py-10">
        <div className="mb-8">
          <h1 className="text-headline-lg text-on-surface mb-3 leading-tight">{data.title}</h1>
          {data.authors?.length > 0 && (
            <p className="text-body-md text-on-surface-variant mb-2">{data.authors.join(", ")}</p>
          )}
          {data.published_date && (
            <p className="text-body-sm text-on-surface-variant/60">{data.published_date}</p>
          )}
        </div>

        {data.abstract && (
          <div className="bg-surface-container-low rounded-xl p-5 border border-outline-variant/40 mb-8">
            <p className="text-[11px] font-semibold text-outline uppercase tracking-wider mb-2">Abstract</p>
            <p className="text-body-md text-on-surface-variant leading-relaxed">{data.abstract}</p>
          </div>
        )}

        {data.executive_summary && (
          <section className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-primary text-[20px]">summarize</span>
              <h2 className="text-title-lg font-semibold text-on-surface">Executive Summary</h2>
            </div>
            <div className="text-body-lg text-on-surface-variant leading-relaxed whitespace-pre-line">{data.executive_summary}</div>
          </section>
        )}

        {data.key_findings && (
          <section className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-primary text-[20px]">science</span>
              <h2 className="text-title-lg font-semibold text-on-surface">Key Findings</h2>
            </div>
            <div className="text-body-lg text-on-surface-variant leading-relaxed whitespace-pre-line">{data.key_findings}</div>
          </section>
        )}

        <footer className="mt-16 pt-8 border-t border-outline-variant/40 text-center">
          <p className="text-body-sm text-on-surface-variant/50">Generated by ScholarFlow — AI Research Paper Assistant</p>
        </footer>
      </main>
    </div>
  );
}
